#:kivy 1.0

<ToDoItemView>:
    orientation: 'horizontal'

    Label:
        text: "X"

        size_hint: (None, None)
        size: (100, 100)

        canvas.before:
            Color:
                rgba: (0.9, 0.6, 0.6, 1)

            Rectangle:
                size: self.size
                pos: self.pos

    BoxLayout:
        orientation: 'vertical'

        Label:
            text: "<to do task title>"

        Label:
            text: "<is completed?>"

